/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { KakaoLoginDto } from '../../models/kakao-login-dto';
import { SignInResponseDto } from '../../models/sign-in-response-dto';

export interface KakaoAuthControllerKakaoLogin$Params {
      body: KakaoLoginDto
}

export function kakaoAuthControllerKakaoLogin(http: HttpClient, rootUrl: string, params: KakaoAuthControllerKakaoLogin$Params, context?: HttpContext): Observable<StrictHttpResponse<SignInResponseDto>> {
  const rb = new RequestBuilder(rootUrl, kakaoAuthControllerKakaoLogin.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<SignInResponseDto>;
    })
  );
}

kakaoAuthControllerKakaoLogin.PATH = '/api/auth/kakao';
