/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AdminDto {

  /**
   * 관리자 계정 생성 시간
   */
  createdAt: string;

  /**
   * 관리자 계정 삭제 시간
   */
  deletedAt?: string | null;

  /**
   * 이메일(로그인ID)
   */
  email: string;

  /**
   * 연속 로그인 실패 횟수
   */
  failCount: number;

  /**
   * 관리자 고유 식별자
   */
  id: string;

  /**
   * 관리자 계정 마지막 로그인 시간
   */
  lastLoginAt?: string | null;

  /**
   * 관리자 계정 잠김 시간
   */
  lockedUntil: string;

  /**
   * 관리자 이름
   */
  name: string;

  /**
   * 관리자 권한 등급
   */
  role: '\uAD00\uB9AC\uC790' | '\uCD5C\uACE0\uAD00\uB9AC\uC790';

  /**
   * 관리자 계정 수정 시간
   */
  updatedAt: string;
}
