/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentDto {

  /**
   * 원본 파일명
   */
  fileName?: string | null;

  /**
   * 첨부파일 고유 식별자
   */
  id: string;

  /**
   * 정렬 순서
   */
  sortOrder: number;

  /**
   * 파일 URL
   */
  url: string;
}
