/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AvailableEventDto {

  /**
   * 행사 종료일
   */
  endDate: string;

  /**
   * 행사 id
   */
  id: string;

  /**
   * 사전 등록 종료일
   */
  preRegEndDate: string;

  /**
   * 사전 등록 시작일
   */
  preRegStartDate: string;

  /**
   * 행사 시작일
   */
  startDate: string;

  /**
   * 행사명
   */
  title: string;
}
