/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface CreateEventDto {

  /**
   * 행사 문의처
   */
  contactNumber?: string | null;

  /**
   * 행사 내용
   */
  content: string;

  /**
   * 행사 종료일
   */
  endDate: string;

  /**
   * 행사 장소
   */
  location?: string | null;

  /**
   * 운영 종료 시간
   */
  operatingEndTime: string;

  /**
   * 운영 시작 시간
   */
  operatingStartTime: string;

  /**
   * 행사 포스터 이미지
   */
  posterImage?: string | null;

  /**
   * 사전 등록 종료일
   */
  preRegEndDate?: string | null;

  /**
   * 사전 등록 시작일
   */
  preRegStartDate?: string | null;

  /**
   * 행사 시작일
   */
  startDate: string;

  /**
   * 행사명
   */
  title: string;
}
