/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventDto {

  /**
   * 행사 문의 연락처
   */
  contactNumber: string;

  /**
   * 행사 내용
   */
  content: string;

  /**
   * 행사 정보 등록일
   */
  createdAt: string;

  /**
   * 행사 종료일
   */
  endDate: string;

  /**
   * 행사 정보 고유 식별자
   */
  id: string;

  /**
   * 행사 장소
   */
  location: string;

  /**
   * 운영 종료 시간
   */
  operatingEndTime: string;

  /**
   * 운영 시작 시간
   */
  operatingStartTime: string;

  /**
   * 포스터 이미지 URL
   */
  posterImage: string;

  /**
   * 사전 등록 마감일
   */
  preRegEndDate: string;

  /**
   * 사전 등록 시작일
   */
  preRegStartDate: string;

  /**
   * 행사 시작일
   */
  startDate: string;

  /**
   * 행사 제목
   */
  title: string;

  /**
   * 행사 정보 수정일
   */
  updatedAt: string;
}
