/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FaqDto {

  /**
   * FAQ 답변
   */
  answer: string;

  /**
   * FAQ 등록일시
   */
  createdAt: string;

  /**
   * FAQ 삭제일시
   */
  deletedAt: string;

  /**
   * FAQ 고유 식별자
   */
  id: string;

  /**
   * FAQ 질문
   */
  question: string;

  /**
   * FAQ 수정일시
   */
  updatedAt: string;
}
