/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentDto } from '../models/attachment-dto';
export interface GalleryDto {

  /**
   * 갤러리 내용
   */
  content?: string | null;

  /**
   * 갤러리 등록일
   */
  createdAt: string;

  /**
   * 갤러리 고유 식별자
   */
  id: string;

  /**
   * 첨부 이미지 목록
   */
  images: Array<AttachmentDto>;

  /**
   * 썸네일 이미지 URL
   */
  thumbnailUrl?: string | null;

  /**
   * 갤러리 제목
   */
  title: string;

  /**
   * 갤러리 수정일
   */
  updatedAt: string;
}
