/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface GalleryCreateDto {

  /**
   * 갤러리 내용
   */
  content?: string | null;

  /**
   * 이미지 URL 목록 (최소 1장, 최대 10장)
   */
  imageUrls: Array<string>;

  /**
   * 갤러리 제목
   */
  title: string;
}
