/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentDto } from '../models/attachment-dto';
export interface InquiryDto {

  /**
   * 답변 내용
   */
  answer?: string | null;

  /**
   * 답변 시각
   */
  answeredAt?: string | null;

  /**
   * 답변자 admin id
   */
  answeredBy?: string | null;

  /**
   * 작성자 이메일
   */
  authorEmail: string;

  /**
   * 작성자 이름
   */
  authorName: string;

  /**
   * 문의 내용
   */
  content: string;

  /**
   * 문의 등록일
   */
  createdAt: string;

  /**
   * 1:1 문의 고유 식별자
   */
  id: string;

  /**
   * 첨부 이미지 목록
   */
  images: Array<AttachmentDto>;

  /**
   * 답변 상태
   */
  status: 'PENDING' | 'COMPLETED';

  /**
   * 문의 제목
   */
  title: string;

  /**
   * 문의 수정일
   */
  updatedAt: string;
}
