/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoticeDto {

  /**
   * 공지사항 내용
   */
  content: string;

  /**
   * 공지사항 등록일시
   */
  createdAt: string;

  /**
   * 공지사항 삭제일시
   */
  deletedAt: string;

  /**
   * 공지사항 고유 식별자
   */
  id: string;

  /**
   * 공지사항 제목
   */
  title: string;

  /**
   * 공지사항 수정일시
   */
  updatedAt: string;
}
