/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PageInfoDto {

  /**
   * 페이지당 항목 수
   */
  limit: number;

  /**
   * 현재 페이지 번호
   */
  page: number;

  /**
   * 현재 페이지 항목 수
   */
  pageItems: number;

  /**
   * 전체 항목 수
   */
  totalItems: number;

  /**
   * 전체 페이지 수
   */
  totalPages: number;
}
