/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PreRegistrationCreateDto {

  /**
   * 동의한 약관 ID 목록
   */
  agreedTermsIds?: Array<string>;

  /**
   * 신청자 이름 (최대 20자)
   */
  applicantName: string;

  /**
   * 연락처 (최대 13자)
   */
  contactNumber: string;

  /**
   * 연결할 행사 id (사전 등록 가능 기간 내인지 서버에서 검증)
   */
  eventId: string;

  /**
   * 연결할 회원 id (비회원 등록 시 생략)
   */
  memberId?: string | null;
}
