/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PreRegistrationDto {

  /**
   * 신청자 이름
   */
  applicantName: string;

  /**
   * 연락처
   */
  contactNumber: string;

  /**
   * 신청일시
   */
  createdAt: string;

  /**
   * 연결된 행사 id
   */
  eventId: string;

  /**
   * 연결된 행사명
   */
  eventTitle: string;

  /**
   * 사전 등록 고유 식별자
   */
  id: string;

  /**
   * 연결된 회원 id (비회원 등록일 경우 null)
   */
  memberId?: string | null;

  /**
   * 연결된 회원 이름 (비회원 등록일 경우 null)
   */
  memberName?: string | null;

  /**
   * 수정일시
   */
  updatedAt: string;
}
