/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AdminDto } from '../models/admin-dto';
export interface SignInResponseDto {

  /**
   * Access Token (짧은 수명)
   */
  accessToken: string;

  /**
   * 관리자 정보
   */
  admin: AdminDto;
}
