/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface SignInAdminDto {

  /**
   * 관리자 이메일
   */
  email: string;

  /**
   * 관리자 비밀번호
   */
  password: string;
}
