/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsAgreementItemDto {

  /**
   * 동의 일시
   */
  agreedAt: string;

  /**
   * 필수 여부
   */
  isRequired: boolean;

  /**
   * 약관 ID
   */
  termsId: string;

  /**
   * 약관 제목
   */
  termsTitle: string;
}
