/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsDto {

  /**
   * 약관 내용
   */
  content: string;

  /**
   * 등록일
   */
  createdAt: string;

  /**
   * 약관 고유 식별자
   */
  id: string;

  /**
   * 필수 약관 여부
   */
  isRequired: boolean;

  /**
   * 약관 제목
   */
  title: string;

  /**
   * 수정일
   */
  updatedAt: string;
}
