/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsCreateDto {

  /**
   * 약관 내용
   */
  content: string;

  /**
   * 약관 제목 (최대 100자)
   */
  title: string;
}
