/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdateBusinessInfoDto {

  /**
   * 주소 (최대 200자)
   */
  address: string;

  /**
   * 연락처 (최대 13자)
   */
  contactNumber: string;

  /**
   * 이메일 (최대 50자, 형식 검증)
   */
  email: string;

  /**
   * 상호명 (최대 50자)
   */
  name: string;

  /**
   * 사업자등록번호 (최대 12자)
   */
  registrationNumber: string;

  /**
   * 대표자명 (최대 20자)
   */
  representativeName: string;
}
