/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UpdatePreRegistrationDto {

  /**
   * 신청자 이름 (최대 20자)
   */
  applicantName: string;

  /**
   * 연락처 (최대 13자)
   */
  contactNumber: string;
}
