/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PageInfoDto } from '../../models/page-info-dto';
import { TermsDto } from '../../models/terms-dto';

export interface TermsControllerFindAll$Params {

/**
 * 페이지 번호
 */
  page?: number;

/**
 * 페이지당 항목 수
 */
  limit?: number;
}

export function termsControllerFindAll(http: HttpClient, rootUrl: string, params?: TermsControllerFindAll$Params, context?: HttpContext): Observable<StrictHttpResponse<{
'items'?: Array<TermsDto>;
'pageInfo'?: PageInfoDto;
}>> {
  const rb = new RequestBuilder(rootUrl, termsControllerFindAll.PATH, 'get');
  if (params) {
    rb.query('page', params.page, {});
    rb.query('limit', params.limit, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<{
      'items'?: Array<TermsDto>;
      'pageInfo'?: PageInfoDto;
      }>;
    })
  );
}

termsControllerFindAll.PATH = '/api/terms';
