services:
  database:
    image: postgres:18-alpine
    container_name: demo-db
    restart: always
    environment:
      POSTGRES_USER: demouser
      POSTGRES_PASSWORD: qwerasdf1234
      POSTGRES_DB: demodb
      TZ: Asia/Seoul
      PGDATA: /data/pgdata

    volumes:
      - demo_database_volume:/data
    ports:
      - "5432:5432"



volumes:
  demo_database_volume:
