/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PreRegistrationDto } from '../../models/pre-registration-dto';
import { PreRegistrationUpdateDto } from '../../models/pre-registration-update-dto';

export interface PreRegistrationControllerUpdate$Params {
  id: string;
      body: PreRegistrationUpdateDto
}

export function preRegistrationControllerUpdate(http: HttpClient, rootUrl: string, params: PreRegistrationControllerUpdate$Params, context?: HttpContext): Observable<StrictHttpResponse<PreRegistrationDto>> {
  const rb = new RequestBuilder(rootUrl, preRegistrationControllerUpdate.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PreRegistrationDto>;
    })
  );
}

preRegistrationControllerUpdate.PATH = '/api/pre-registration/{id}';
