/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export { ApiConfiguration } from './api-configuration';
export { RequestBuilder } from './request-builder';
export type { StrictHttpResponse } from './strict-http-response';
export { Api } from './api';

export type { AdminDto } from './models/admin-dto';
export type { AdminSignInDto } from './models/admin-sign-in-dto';

export type { AppControllerGetData$Params as AppControllerGetData$Params } from './fn/app/app-controller-get-data';
export { appControllerGetData as appControllerGetData } from './fn/app/app-controller-get-data';
export type { AdminControllerGethello$Params as AdminControllerGethello$Params } from './fn/admin/admin-controller-gethello';
export { adminControllerGethello as adminControllerGethello } from './fn/admin/admin-controller-gethello';
export type { AdminControllerFindAll$Params as AdminControllerFindAll$Params } from './fn/admin/admin-controller-find-all';
export { adminControllerFindAll as adminControllerFindAll } from './fn/admin/admin-controller-find-all';
export type { AdminControllerSignin$Params as AdminControllerSignin$Params } from './fn/admin/admin-controller-signin';
export { adminControllerSignin as adminControllerSignin } from './fn/admin/admin-controller-signin';
