/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export type { AdminDto } from './models/admin-dto';
export type { AdminSignInDto } from './models/admin-sign-in-dto';
export type { AttachmentDto } from './models/attachment-dto';
export type { AvailableEventDto } from './models/available-event-dto';
export type { BusinessInfoDto } from './models/business-info-dto';
export type { BusinessInfoUpdateDto } from './models/business-info-update-dto';
export type { EventCreateDto } from './models/event-create-dto';
export type { EventDto } from './models/event-dto';
export type { FaqCreateDto } from './models/faq-create-dto';
export type { FaqDto } from './models/faq-dto';
export type { GalleryCreateDto } from './models/gallery-create-dto';
export type { GalleryDto } from './models/gallery-dto';
export type { InquiryAnswerDto } from './models/inquiry-answer-dto';
export type { InquiryDto } from './models/inquiry-dto';
export type { NoticeCreateDto } from './models/notice-create-dto';
export type { NoticeDto } from './models/notice-dto';
export type { PageInfoDto } from './models/page-info-dto';
export type { PreRegistrationCreateDto } from './models/pre-registration-create-dto';
export type { PreRegistrationDto } from './models/pre-registration-dto';
export type { PreRegistrationUpdateDto } from './models/pre-registration-update-dto';
export type { SignInResponseDto } from './models/sign-in-response-dto';
export type { TermsAgreementItemDto } from './models/terms-agreement-item-dto';
export type { TermsCreateDto } from './models/terms-create-dto';
export type { TermsDto } from './models/terms-dto';
