/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface AttachmentDto {

  /**
   * 첨부파일 식별자
   */
  id: string;

  /**
   * 정렬 순서
   */
  sortOrder?: number;

  /**
   * 파일 URL
   */
  url: string;
}
