/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface BusinessInfoDto {

  /**
   * 주소
   */
  address: string;

  /**
   * 연락처
   */
  contactNumber: string;

  /**
   * 이메일
   */
  email: string;

  /**
   * 사업자 정보 고유 식별자
   */
  id: string;

  /**
   * 상호명
   */
  name: string;

  /**
   * 사업자등록번호
   */
  registrationNumber: string;

  /**
   * 대표자명
   */
  representativeName: string;
}
