/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface EventDto {

  /**
   * 문의처(연락처)
   */
  contactNumber?: string;

  /**
   * 행사 상세 내용
   */
  content: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 행사 종료일
   */
  endDate: string;

  /**
   * 행사 식별자
   */
  id: string;

  /**
   * 행사 장소
   */
  location?: string;

  /**
   * 운영 종료 시간 (HH:mm 형식)
   */
  operatingEndTime: string;

  /**
   * 운영 시작 시간 (HH:mm 형식)
   */
  operatingStartTime: string;

  /**
   * 포스터 이미지 URL
   */
  posterImage?: string;

  /**
   * 사전등록 종료일
   */
  preRegEndDate?: string;

  /**
   * 사전등록 시작일
   */
  preRegStartDate?: string;

  /**
   * 행사 시작일
   */
  startDate: string;

  /**
   * 행사명
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
