/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface FaqDto {

  /**
   * 답변
   */
  answer: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * FAQ 식별자
   */
  id: string;

  /**
   * 질문
   */
  question: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
