/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { AttachmentDto } from '../models/attachment-dto';
export interface GalleryDto {

  /**
   * 내용
   */
  content?: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 갤러리 식별자
   */
  id: string;

  /**
   * 첨부 이미지 목록
   */
  images: Array<AttachmentDto>;

  /**
   * 썸네일 이미지 URL
   */
  thumbnailUrl?: string | null;

  /**
   * 제목
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
