/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface InquiryDto {

  /**
   * 답변
   */
  answer?: string;

  /**
   * 답변 일시
   */
  answeredAt?: string;

  /**
   * 답변자
   */
  answeredBy?: string;

  /**
   * 내용
   */
  content: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 문의 식별자
   */
  id: string;

  /**
   * 회원 식별자
   */
  memberId: string;

  /**
   * 처리 상태
   */
  status: 'PENDING' | 'COMPLETED';

  /**
   * 제목
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
