/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberDto {

  /**
   * 가입일
   */
  createdAt: string;

  /**
   * 삭제일
   */
  deletedAt?: string | null;

  /**
   * 이메일
   */
  email: string;

  /**
   * 회원 고유 식별자
   */
  id: string;

  /**
   * 회원 이름
   */
  name: string;

  /**
   * 수정일
   */
  updatedAt: string;
}
