/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface MemberSignUpDto {

  /**
   * 이메일
   */
  email: string;

  /**
   * 이름
   */
  name: string;

  /**
   * 비밀번호
   */
  password: string;
}
