/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface NoticeDto {

  /**
   * 내용
   */
  content: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 공지사항 식별자
   */
  id: string;

  /**
   * 제목
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
