/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PreRegistrationCreateDto {

  /**
   * 동의한 약관 ID 배열
   */
  agreedTermsIds?: Array<string>;

  /**
   * 신청자 이름
   */
  applicantName: string;

  /**
   * 연락처
   */
  contactNumber: string;

  /**
   * 행사 ID
   */
  eventId: string;
}
