/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface PreRegistrationDto {

  /**
   * 신청자 이름
   */
  applicantName: string;

  /**
   * 연락처
   */
  contactNumber: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 행사 ID
   */
  eventId: string;

  /**
   * 사전 등록 식별자
   */
  id: string;
}
