/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { MemberDto } from '../models/member-dto';
export interface SignInResponseDto {

  /**
   * Access Token
   */
  accessToken: string;

  /**
   * 회원 정보
   */
  member: MemberDto;
}
