/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface TermsDto {

  /**
   * 약관 내용
   */
  content: string;

  /**
   * 생성 일시
   */
  createdAt: string;

  /**
   * 약관 식별자
   */
  id: string;

  /**
   * 필수 여부
   */
  isRequired: boolean;

  /**
   * 약관 제목
   */
  title: string;

  /**
   * 수정 일시
   */
  updatedAt: string;
}
