/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { InquiryAnswerDto } from '../../models/inquiry-answer-dto';
import { InquiryDto } from '../../models/inquiry-dto';

export interface InquiryControllerUpdateAnswer$Params {
  id: string;
      body: InquiryAnswerDto
}

export function inquiryControllerUpdateAnswer(http: HttpClient, rootUrl: string, params: InquiryControllerUpdateAnswer$Params, context?: HttpContext): Observable<StrictHttpResponse<InquiryDto>> {
  const rb = new RequestBuilder(rootUrl, inquiryControllerUpdateAnswer.PATH, 'patch');
  if (params) {
    rb.path('id', params.id, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<InquiryDto>;
    })
  );
}

inquiryControllerUpdateAnswer.PATH = '/api/inquiry/{id}';
