/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDto } from '../../models/member-dto';
import { MemberSignUpDto } from '../../models/member-sign-up-dto';

export interface MemberControllerSignup$Params {
      body: MemberSignUpDto
}

export function memberControllerSignup(http: HttpClient, rootUrl: string, params: MemberControllerSignup$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberDto>> {
  const rb = new RequestBuilder(rootUrl, memberControllerSignup.PATH, 'post');
  if (params) {
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberDto>;
    })
  );
}

memberControllerSignup.PATH = '/api/members/signup';
