/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { MemberDto } from '../../models/member-dto';

export interface MemberControllerMe$Params {
}

export function memberControllerMe(http: HttpClient, rootUrl: string, params?: MemberControllerMe$Params, context?: HttpContext): Observable<StrictHttpResponse<MemberDto>> {
  const rb = new RequestBuilder(rootUrl, memberControllerMe.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<MemberDto>;
    })
  );
}

memberControllerMe.PATH = '/api/members/me';
