/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { EventDto } from '../../models/event-dto';

export interface EventControllerFindAvailableEvents$Params {
}

export function eventControllerFindAvailableEvents(http: HttpClient, rootUrl: string, params?: EventControllerFindAvailableEvents$Params, context?: HttpContext): Observable<StrictHttpResponse<Array<EventDto>>> {
  const rb = new RequestBuilder(rootUrl, eventControllerFindAvailableEvents.PATH, 'get');
  if (params) {
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<Array<EventDto>>;
    })
  );
}

eventControllerFindAvailableEvents.PATH = '/api/events/available-events';
